steps:
  # _APP_ENV, _APP_NAME, _CLUSTER, _REGION need to be defined in the build trigger
  - name: 'gcr.io/cloud-builders/docker'
    id: Build
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/$_APP_NAME:$SHORT_SHA'
      - '.'
    timeout: 600s

  - name: 'gcr.io/cloud-builders/docker'
    id: Push
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/$_APP_NAME:$SHORT_SHA'

  - name: gcr.io/cloud-builders/docker
    id: Tag
    args:
      - 'tag'
      - 'gcr.io/$PROJECT_ID/$_APP_NAME:$SHORT_SHA'
      - 'gcr.io/$PROJECT_ID/$_APP_NAME:$_APP_ENV'

images:
  - 'gcr.io/$PROJECT_ID/$_APP_NAME:$SHORT_SHA'
  - 'gcr.io/$PROJECT_ID/$_APP_NAME:$_APP_ENV'

tags: [$_APP_NAME, $_APP_ENV]
